version: "3.3"
services:
  website:
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html
    ports:
      - 80:80
    networks:
      - pozos_network
    depends_on:
      - api
  api:
    build: "./simple_api"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 5000:5000
    networks:
      - pozos_network
  p_registry:
    image : registry:2
    ports:
     - 4999:5000
    environment:
     - REGISTRY_STORAGE_DELETE_ENABLED=true
    networks:
     - registry_network
  registry_ui:
    image: joxit/docker-registry-ui:static
    depends_on:
     - p_registry
    networks:
     - registry_network
    ports:
     - 8090:80
    environment:
     - REGISTRY8URL=http://private_registry:5000
     - DELETE_IMAGE=true
     - REGISTRY_TITLE=CherifBachir
networks:
  pozos_network:
  registry_network
